spring:
  application:
    name: smarthr
  profiles:
    active: qa
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://172.24.100.101:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:YOUR LOCAL BOT TOKEN HERE}

management:
  endpoints:
    web:
      exposure:
        include: health

build:
  version: "3.0.0"