spring:
  application:
    name: smarthr
  profiles:
    active: qa
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:$Rith$9990}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:YOUR LOCAL BOT TOKEN HERE}

management:
  endpoints:
    web:
      exposure:
        include: health

build:
  version: "3.0.0"